spring:
    profiles:
        active: development
    #konfigurasi jackson
    jackson:
        serialization:
            indent-output: true

    # spring datasource jpa
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/naru_project?autoReconnect=true
        username: root
        password: telkomdds
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000

    # spring hibernate
    jpa:
        generate-ddl: true
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
